"""originpro 接口的 Protocol 定义。

为 originpro 模块中常用的对象定义 structural typing 接口，
替代 Any 类型，提供更好的类型检查和 IDE 补全支持。

注意：这些 Protocol 只定义了项目实际使用到的方法子集。
"""

from __future__ import annotations

from typing import Any, Iterable, Protocol, runtime_checkable


class WorksheetProtocol(Protocol):
    """工作表对象接口。"""

    @property
    def rows(self) -> int: ...

    @property
    def cols(self) -> int: ...

    @property
    def name(self) -> str: ...

    def get_col(self, index: int) -> Any: ...

    def to_list(self, col_index: int) -> list: ...

    def cols_axis(self, spec: str) -> None: ...

    def get_labels(self, label_type: str) -> list[str]: ...

    def from_list(self, col_index: int, data: list) -> None: ...


class GraphLayerProtocol(Protocol):
    """图层对象接口。"""

    def add_plot(self, wks: Any, **kwargs: Any) -> Any: ...

    def rescale(self) -> None: ...

    def plot(self, index: int) -> Any: ...

    def plot_list(self) -> list: ...

    def remove_plot(self, index: int) -> None: ...

    def group(self, *args: Any) -> None: ...

    @property
    def num_plots(self) -> int: ...

    def set_xlim(self, begin: float = ..., end: float = ..., step: float = ...) -> None: ...

    def set_ylim(self, begin: float = ..., end: float = ..., step: float = ...) -> None: ...

    def axis(self, name: str) -> Any: ...


class GraphProtocol(Protocol):
    """图表对象接口。"""

    @property
    def name(self) -> str: ...

    @property
    def lname(self) -> str: ...

    @lname.setter
    def lname(self, value: str) -> None: ...

    def __getitem__(self, index: int) -> GraphLayerProtocol: ...

    def __len__(self) -> int: ...

    def save_fig(self, path: str, **kwargs: Any) -> str: ...

    def add_layer(self, layer_type: int) -> GraphLayerProtocol: ...

    def copy_page(self, fmt: str, dpi: int, quality: int, transparent: bool) -> None: ...


@runtime_checkable
class OriginProProtocol(Protocol):
    """originpro 模块的操作接口。

    定义了通过 OriginManager.execute() 传入回调函数的 `op` 参数接口。
    """

    def find_sheet(self, kind: str, name: str) -> WorksheetProtocol | None: ...

    def find_graph(self, name: str) -> GraphProtocol | None: ...

    def new_graph(self, template: str = ...) -> GraphProtocol: ...

    def new_sheet(self, **kwargs: Any) -> WorksheetProtocol: ...

    def pages(self, kind: str) -> Iterable[Any]: ...

    def save(self, path: str = ...) -> None: ...

    def open(self, file: str = ..., readonly: bool = ...) -> None: ...

    def new(self) -> None: ...

    def lt_exec(self, command: str) -> Any: ...

    def path(self, kind: str) -> str: ...

    def set_show(self, visible: bool) -> None: ...

    def exit(self) -> None: ...
